from fastapi.testclient import TestClient

import app.routes.v2 as v2_routes
from app.main import app


client = TestClient(app)


def test_list_clients() -> None:
    response = client.get("/v2/clients")

    assert response.status_code == 200
    data = response.json()
    assert len(data) == 3
    assert any(entry["id"] == "alex_chen" for entry in data)


def test_get_client_analytics() -> None:
    response = client.get("/v2/clients/alex_chen/analytics")

    assert response.status_code == 200
    data = response.json()
    assert data["client_id"] == "alex_chen"
    assert data["net_worth_sgd"] > 0


def test_get_client_analytics_not_found() -> None:
    response = client.get("/v2/clients/nobody/analytics")

    assert response.status_code == 404


def test_get_client_wellness() -> None:
    response = client.get("/v2/clients/alex_chen/wellness")

    assert response.status_code == 200
    data = response.json()
    assert 0 <= data["wellness_score"] <= 100


def test_get_events() -> None:
    response = client.get("/v2/events")

    assert response.status_code == 200
    assert len(response.json()) >= 3


def test_event_impact() -> None:
    response = client.post(
        "/v2/events/impact",
        json={"event_id": "evt_crypto_001", "client_id": "alex_chen"},
    )

    assert response.status_code == 200
    data = response.json()
    assert data["severity"] in {"LOW", "MODERATE", "HIGH", "CRITICAL"}
    assert data["total_exposure_pct"] > 0


def test_research_search() -> None:
    response = client.post(
        "/v2/research/search",
        json={"query": "liquidity buffer Singapore"},
    )

    assert response.status_code == 200
    data = response.json()
    assert len(data["results"]) >= 1
    assert data["results"][0]["score"] > 0


def test_generate_alert_seeded(monkeypatch) -> None:
    monkeypatch.setattr(v2_routes, "generate_alert_brief", lambda *args: None)

    response = client.post(
        "/v2/alerts/generate",
        json={"event_id": "evt_crypto_001", "client_id": "alex_chen"},
    )

    assert response.status_code == 200
    data = response.json()
    assert "Digital Asset" in data["subject"]
    assert data["grounding_validated"] is True
    assert len(data["recommended_actions"]) >= 1


def test_copilot_query_top_actions(monkeypatch) -> None:
    monkeypatch.setattr(v2_routes, "generate_copilot_response", lambda *args: None)

    response = client.post(
        "/v2/copilot/query",
        json={
            "client_id": "alex_chen",
            "question": "What are the top 3 actions for Alex this quarter?",
        },
    )

    assert response.status_code == 200
    data = response.json()
    assert len(data["structured_actions"]) >= 2
    assert data["grounding_validated"] is True


def test_copilot_query_property(monkeypatch) -> None:
    monkeypatch.setattr(v2_routes, "generate_copilot_response", lambda *args: None)

    response = client.post(
        "/v2/copilot/query",
        json={
            "client_id": "alex_chen",
            "question": "Can Alex afford a property upgrade?",
        },
    )

    assert response.status_code == 200
    data = response.json()
    assert "property" in data["answer"].lower() or "mortgage" in data["answer"].lower()


def test_generate_alert_prefers_llm_output_when_available(monkeypatch) -> None:
    monkeypatch.setattr(
        v2_routes,
        "generate_alert_brief",
        lambda manifest, headline, client_name: {
            "subject": "LLM Alert",
            "brief": "Generated by LLM.",
            "recommended_actions": ["Call the client today."],
            "house_view_citations": [
                {"doc": "digital-asset-risk-playbook.md", "excerpt": "LLM grounded."}
            ],
        },
        raising=False,
    )

    response = client.post(
        "/v2/alerts/generate",
        json={"event_id": "evt_crypto_001", "client_id": "alex_chen"},
    )

    assert response.status_code == 200
    assert response.json()["subject"] == "LLM Alert"


def test_copilot_query_prefers_llm_output_when_available(monkeypatch) -> None:
    monkeypatch.setattr(
        v2_routes,
        "generate_copilot_response",
        lambda client_id, question: {
            "answer": "LLM copilot answer.",
            "structured_actions": [
                {
                    "rank": 1,
                    "action": "Do the thing.",
                    "rationale": "Metric-backed.",
                    "urgency": "HIGH",
                }
            ],
        },
        raising=False,
    )

    response = client.post(
        "/v2/copilot/query",
        json={
            "client_id": "alex_chen",
            "question": "What are the top 3 actions for Alex this quarter?",
        },
    )

    assert response.status_code == 200
    assert response.json()["answer"] == "LLM copilot answer."
